#!/usr/bin/env bash
# ---------------------------------------------------------------------
# Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------
# Build the static bash (see Dockerfile) and extract it to the vendored path, alongside
# a generated checksum/provenance file. Re-run and commit both whenever the Dockerfile
# or bash version changes.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$SCRIPT_DIR/bash-static-x86_64"
SUMS="$OUT.sha256"

docker build --platform linux/amd64 -t aiha-bash-static "$SCRIPT_DIR"
cid="$(docker create --platform linux/amd64 aiha-bash-static)"
trap 'docker rm "$cid" >/dev/null 2>&1 || true' EXIT
docker cp "$cid:/bash" "$OUT"
chmod +x "$OUT"

base_ref="$(awk '/^FROM /{print $2; exit}' "$SCRIPT_DIR/Dockerfile")"
base_digest="$(docker image inspect --format '{{index .RepoDigests 0}}' "$base_ref" 2>/dev/null || echo unknown)"
toolchain="$(
    docker run --rm --platform linux/amd64 aiha-bash-static sh -c '
        printf "bash:      %s\n" "$(/bash --version | head -1)"
        printf "alpine:    %s\n" "$(. /etc/os-release; echo "$PRETTY_NAME")"
        printf "gcc:       %s\n" "$(gcc -dumpfullversion)"
        printf "musl:      %s\n" "$(apk info -v musl | grep "^musl-" | head -1)"
    ' 2>/dev/null || printf 'bash:      unknown\nalpine:    unknown\ngcc:       unknown\nmusl:      unknown\n'
)"

{
    echo "# Generated by build.sh -- do not edit by hand."
    echo "#"
    echo "# Provenance for the vendored static bash. Verify the committed binary with:"
    echo "#     sha256sum -c $(basename "$SUMS")"
    echo "#"
    echo "# base:      $base_ref"
    echo "# digest:    $base_digest"
    echo "$toolchain" | sed 's/^/# /'
    echo "# size:      $(wc -c <"$OUT") bytes"
    echo "#"
    echo "# This identifies the blob that is committed; it is not a reproducibility"
    echo "# guarantee. The base image is a floating tag and the apk toolchain is"
    echo "# unpinned, so a later rebuild can pick up a newer musl/gcc and produce a"
    echo "# different hash from this same recipe. A mismatch means \"built at a"
    echo "# different time\", not necessarily \"built from something else\"."
    (cd "$SCRIPT_DIR" && sha256sum "$(basename "$OUT")")
} >"$SUMS"

file "$OUT"
cat "$SUMS"
echo "Wrote $OUT and $SUMS"
