
name: Android Apps Build & Test

on:
  # Allows this workflow to be callable
  workflow_call:
    inputs:
      run_tests:
        type: boolean
        default: false

      build_docker:
        type: boolean
        default: false

      docker_tag:
        type: string
        default: commit_sha

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      run_tests:
        description: Run Android Build & Test
        type: boolean
        default: true

      build_docker:
        type: boolean
        default: true
        description: Build Docker Container

      docker_tag:
        type: string
        default: commit_sha
        description: Docker Container Tag

jobs:
  build_android_docker:
    name: Build Android Builder Docker Image
    runs-on: ubuntu-latest
    if: inputs.build_docker || inputs.docker_tag == 'commit_sha'
    outputs:
      image_tag: ${{ steps.tag.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: kwatson309
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tag
        id: tag
        run: |
          if [[ "${{ inputs.docker_tag }}" == "change_sha" ]]; then
            echo "image_tag=${{ github.sha }}" >> $GITHUB_OUTPUT
          else
            echo "image_tag=${{ inputs.docker_tag }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./scripts/ci/docker/android_builder.dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/android_builder:${{ steps.tag.outputs.image_tag }}
          cache-from: type=gha,scope=android_builder
          cache-to: type=gha,scope=android_builder,mode=max

  build_and_verify_android:
    name: Build and Verify Android Apps
    if: always() && inputs.run_tests
    runs-on: ubuntu-latest
    needs: build_android_docker
    container:
      image: ${{ format('ghcr.io/{0}/android_builder:{1}', github.repository, needs.build_android_docker.result == 'success' && needs.build_android_docker.outputs.image_tag || inputs.docker_tag ) }}
    defaults:
      run:
        shell: bash
    permissions:
      id-token: write
      packages: read
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup AWS Credentials
        uses: ./.github/actions/configure-multiple-aws-roles
        with:
          role-to-assume: ${{ secrets.QAIHA_CI_AWS_ROLE_ARN }}
          role-duration-seconds: 7200
          profile: qaihm
          aws-region: us-west-2

      - name: Install Python Deps
        id: install_deps
        run: |
          python3 scripts/build_and_test.py --venv $VENV_PATH install_deps

      - name: Configure Hub Credentials
        id: set_hub_creds
        run: |
          source "$VENV_PATH/bin/activate" && \
            qai-hub configure --api_token "${{ secrets.HUB_USER_TOKEN_PROD }}" \
            --no-verbose

      - name: Run Tests
        id: run_tests
        run: |
          source "$VENV_PATH/bin/activate" && python -m pytest --pyargs qai_hub_apps.test.test_apps -s -vv -k android

  delete_temporary_container_tag:
    name: Delete Temporary Container Tag
    needs: ['build_android_docker', 'build_and_verify_android']
    if: always() && inputs.docker_tag == 'commit_sha' && needs.build_android_docker.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
    env:
      GH_TOKEN: ${{ github.token }}
      PACKAGE_VERSIONS_API_URL: ${{ format('/orgs/{0}/packages/container/ai-hub-apps-internal%2fandroid_builder/versions', github.repository_owner) }}
    steps:
      - name: Delete Temporary Container Tag
        # This can fail if the tag doesn't exist (eg if the docker was fully cached already). In that case this will 404. We can ignore the 404.
        continue-on-error: true
        run: |
          # Remove the temporary container tag used for this action.
          # This allows the package registry to clean up cached layers.
          TAG_ID=$(gh api "${PACKAGE_VERSIONS_API_URL}" | jq --arg tag "${{ needs.build_android_docker.outputs.image_tag }}" '.[] | select(.metadata.container.tags[] == $tag) | .id')
          gh api --method DELETE "${PACKAGE_VERSIONS_API_URL}/${TAG_ID}"
