name: Windows Apps Build & Test

on:
  # Allows this workflow to be callable
  workflow_call:
    inputs:
      run_tests:
        type: boolean
        default: false

      build_docker:
        type: boolean
        default: false

      docker_tag:
        type: string
        default: commit_sha

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      run_tests:
        description: Run Windows Build & Test
        type: boolean
        default: true

      build_docker:
        type: boolean
        default: true
        description: Build Docker Container

      docker_tag:
        type: string
        default: commit_sha
        description: Docker Container Tag

jobs:
  build_windows_docker:
    name: Build Windows Builder Docker Image
    runs-on: windows-latest
    if: inputs.build_docker || inputs.docker_tag == 'commit_sha'
    outputs:
      image_tag: ${{ steps.tag.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          lfs: false

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: kwatson309
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tag
        id: tag
        shell: pwsh
        run: |
          if ('${{ inputs.docker_tag }}' -eq 'change_sha') {
            "image_tag=${{ github.sha }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          } else {
            "image_tag=${{ inputs.docker_tag }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          }

      - name: Build and push Docker image
        id: build
        shell: pwsh
        env:
          DOCKER_BUILDKIT: 0
        run: |
          docker build `
            -f ./scripts/ci/docker/windows_builder.dockerfile `
            -t ghcr.io/${{ github.repository }}/windows_builder:${{ steps.tag.outputs.image_tag }} `
            .
          docker push ghcr.io/${{ github.repository }}/windows_builder:${{ steps.tag.outputs.image_tag }}

  build_and_verify_windows:
    name: Build and Verify Windows Apps
    if: always() && inputs.run_tests
    runs-on: windows-latest
    needs: build_windows_docker
    defaults:
      run:
        shell: pwsh
    permissions:
      id-token: write
      packages: read
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup AWS Credentials
        uses: ./.github/actions/configure-multiple-aws-roles
        with:
          role-to-assume: ${{ secrets.QAIHA_CI_AWS_ROLE_ARN }}
          role-duration-seconds: 7200
          profile: qaihm
          aws-region: us-west-2

      - name: Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Image
        id: pull_docker_image
        run: |
            $image = "ghcr.io/${{ github.repository }}/windows_builder:${{ needs.build_windows_docker.outputs.image_tag || inputs.docker_tag }}"
            docker pull $image && docker tag $image win_ci

      - name: Prepare and Run Tests
        id: prep_run_tests
        run: |
          $awsDir = Join-Path $env:USERPROFILE ".aws"
          docker run `
          --rm `
          -e HUB_USER_TOKEN_PROD=${{ secrets.HUB_USER_TOKEN_PROD }} `
          -e AWS_SHARED_CREDENTIALS_FILE="C:\aws\credentials" `
          -e AWS_CONFIG_FILE="C:\aws\config" `
          -e AWS_PROFILE="qaihm" `
          -v "$env:GITHUB_WORKSPACE`:C:\Code" `
          -v "$awsDir`:C:\aws" `
          -w C:\Code `
            win_ci -File scripts\ci\windows\prep_run_tests.ps1;

  delete_temporary_container_tag:
    name: Delete Temporary Container Tag
    needs: ['build_windows_docker', 'build_and_verify_windows']
    if: always() && inputs.docker_tag == 'commit_sha' && needs.build_windows_docker.result == 'success'
    runs-on: windows-latest
    permissions:
      id-token: write
      packages: write
    env:
      GH_TOKEN: ${{ github.token }}
      PACKAGE_VERSIONS_API_URL: ${{ format('/orgs/{0}/packages/container/ai-hub-apps-internal%2fwindows_builder/versions', github.repository_owner) }}
    steps:
      - name: Delete Temporary Container Tag
        # This can fail if the tag doesn't exist (eg if the docker was fully cached already). In that case this will 404. We can ignore the 404.
        continue-on-error: true
        shell: pwsh
        run: |
          # Remove the temporary container tag used for this action.
          # This allows the package registry to clean up cached layers.
          $tag = "${{ needs.build_windows_docker.outputs.image_tag }}"
          $url = "$env:PACKAGE_VERSIONS_API_URL"
          $response = gh api $url | ConvertFrom-Json
          $tagId = $response |
            Where-Object { $_.metadata.container.tags -contains $tag } |
            Select-Object -ExpandProperty id
          gh api --method DELETE "$url/$tagId"
